### PR TITLE
Add RawSocket transport for Node

### PR DESCRIPTION
**Pull request by swordofpain**
This PR adds RawSocket transport capability to Node applications using Autobahn|JS

### CODE REVIEW

**Comment by oberstet** [comment]
cool! but this only works in node, not browser? how did you test it?

**Comment by swordofpain** [comment]
We can't open a TCP socket in the browser, as stated in the RawSocket doc page for crossbar. Testing was made by declaring a single rawsocket transport in the configuration. I'll write some more protocol checks between now and the end of the week

**Comment by oberstet** [comment]
You are of course right. I should get some sleep;) rgd tests: awesome! are you testing against Crossbar.io?

**Comment by swordofpain** [comment]
Yes. Ill probably need to get AutobahnPython not to choke on PING/PONG packets to do that properly

**Comment by swordofpain** [comment]
When using the bundled version (built using `make bundle`), Autobahn is unable to make a connection (it fails with `reason: unsupported`) even when using WebSockets. I'm trying to trace the root cause.

**Comment by swordofpain** [comment]
Work on the tests is underway, but I'm having troubles with `nodeunit` which doesn't seem to register my `test.done()` calls half of the time. I'll keep working on it.

**Comment by oberstet** [comment]
thanks for letting us know and for the testing

**Pull request merged**
