### PR TITLE
Test rawsocket protocol

### PR DESCRIPTION
**Pull request by swordofpain**
This tests the RawSocket protocol and fixes a couple of bugs

### CODE REVIEW

**Comment by oberstet** [comment]
@swordofpain thanks! the PR introduces a new dependency `lodash.defaults`. Why?

**Comment by swordofpain** [comment]
Well, I probably could rewrite this function, but using a supported one made more sense to me (also it can probably be useful to other objects that rely on an `options` dict).

**Comment by oberstet** [comment]
The introduction of a new dependency is nothing we do quickly. Up till now, I did not miss anything rgd treatment of options. And I dont see how rawsocket would change that. What existing code could profit from that library?

That being said: it doesnt mean we cant take any new dependency. We just need to have good reasons ..

Maybe this is different from the usual policy with JS projects, but in Autobahn case, we need to have some project management, since there are "serious" apps out there that _rely_ on Autobahn ..

**Comment by swordofpain** [comment]
I get your point. I implemented a similar function in `lib/util.js` and removed the dep.

**Comment by goeddea** [comment]
@swordofpain - Just wanted to add documentation for the RawSocket support. Could you provide me with a working example for this? Easiest would be a "hello:nodejs" adapted to use RawSocket.

**Pull request merged**
